### ISSUE TITLE
Module does not work out of the box

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport-cluster-terraform#12]
The module does not work with the current versions of Teleport.  PR https://github.com/gravitational/teleport-cluster-terraform/pull/11 collects some of the minimum changes ported over from the root example that make this module functional again

**Comment by wadells** [comment]
We're deprecating this repo in favor of https://github.com/gravitational/teleport/tree/master/examples/aws/terraform, exactly due to issues like this.
