### ISSUE TITLE
ASG launch configurations are deprecated

### ISSUE THREAD

**Issue by bpdohall** [gravitational/teleport-cluster-terraform#9]
AWS is sending email notices to customers prompting them to convert from launch configs to launch templates. 

Our reference terraform module is using launch configurations to configure EC2 instances: https://github.com/gravitational/teleport-cluster-terraform/blob/master/node_asg.tf#L37

Anyone running the AWS tooling to identify in-use launch configs will have the launch configs for their Teleport cluster created by this module show up in their report. (ref: [AWS Blog Post](https://aws.amazon.com/blogs/compute/amazon-ec2-auto-scaling-will-no-longer-add-support-for-new-ec2-features-to-launch-configurations/))

To mitigate, the ASG in the reference module should use a launch template instead of a launch configuration.

**Comment by wadells** [comment]
This was fixed in https://github.com/gravitational/teleport/commit/00f99f478803253a467367429af3366c7ebd9681.

Any future folks stumbling across this, please use the terraform at https://github.com/gravitational/teleport/tree/master/examples/aws/terraform instead.
